// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjivfywgkiwjvpquxndg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqaXZmeXdna2l3anZwcXV4bmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNDg5MzQsImV4cCI6MjA1NDcyNDkzNH0.o6X6W_rrdC-yTctwZUALOsTzRqxC7R5atrGz_JaOqSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);